agregar perfil de Norbey Vasquez
makeitrealcamp/top-v20 pull request #13
Opened 2022-02-24 16:14 UTC by nvasquezt

### Descripción
Perfil de Norbey Vasquez Agregado, archivo readme modificado

### Feeling
[//]: <> (Como te sientes con este PR? la solucion que entregas como te hace sentir?)
- [ ] 🤙 Solucion rapida
- [ x] 👌 Terminado y listo
- [ ] 🤞 Espero que esto funcione, por favor revisar cuidadosamente

### Tickets
5fdfd7e 

### Cómo probar?
Observar que el link asociado al nombre "Norbey Vasquez"  lleve al archivo norbey-vasquez.md, donde se encuentra la información anexada.

### Scope

- [ ] 🐞 Bugfix (non-breaking changes que resuelve un problema
- [ ] 💚 Mejora (non-breaking change que agrega/modifica funcionalidad a una característica existente)
- [x ] ⚡️ Nueva característica/feature (non-breaking change que agrega una nueva característica)
- [ ] ⚠️ Breaking change (cambio que no es compatible con versiones anteriores y/o cambia la funcionalidad actual)

2022-02-24 16:45 UTC, julians55 requested changes
En tu archivo norbey-vazquez.md olvidaste cambiar la plantilla de tu nombre!

2022-02-24 16:49 UTC, nvasquezt commented
> En tu archivo norbey-vazquez.md olvidaste cambiar la plantilla de tu nombre!

Muchas gracias!

Ajustes realizados

2022-02-24 17:01 UTC, julians55 approved these changes
Listo, perfecto!

2022-02-25 19:12 UTC, khriztianmoreno approved these changes

2022-02-25 19:13 UTC, merged