Agregar perfil de wendy medina
makeitrealcamp/top-v20 pull request #17
Opened 2022-02-24 16:43 UTC by endyleyms

### Descripción
[//]: <> (Agregar el perfil de Wendy Medina)

### Feeling
[//]: <> (Como te sientes con este PR? la solucion que entregas como te hace sentir?)
- [ ] 🤙 Solucion rapida
- [ ] 👌 Terminado y listo
- [ x] 🤞 Espero que esto funcione, por favor revisar cuidadosamente

### Tickets
[//]: <> (El numero del ticket asociado a este PR)

### Cómo probar?
[//]: <> (Pasos necesarios para probar esta funcionalidad)

### Screenshots (si es aplicable)
[//]: <> (Capturas de pantalla que ayuden a entender que hiciste en este PR)

### Scope

- [ ] 🐞 Bugfix (non-breaking changes que resuelve un problema
- [ ] 💚 Mejora (non-breaking change que agrega/modifica funcionalidad a una característica existente)
- [ ] ⚡️ Nueva característica/feature (non-breaking change que agrega una nueva característica)
- [ ] ⚠️ Breaking change (cambio que no es compatible con versiones anteriores y/o cambia la funcionalidad actual)

2022-02-24 16:49 UTC, santy289 approved these changes, later dismissed

2022-02-24 16:53 UTC, jlopezsa commented
Hola Wendy,
Revisando el archivo README.md vi que existe un espacio entre las llaves y los paréntesis de la siguiente línea [Wendy Medina] (profiles/wendy-medina.md) y puede que el link no se muestre correctamente.
Intenta quitar el espacio para que se reconozca bien el comando.

Con espacio aparecerá algo así:
[Wendy Medina] (profiles/wendy-medina.md)

Quitando el espacio, el link se mostrará como:
[Wendy Medina](profiles/wendy-medina.md)

2022-02-24 16:59 UTC, endyleyms commented
Hola, muchas gracias por tu comentario. tuve varios inconvenientes. Creo que ya los resolvi

2022-02-24 17:20 UTC, santy289 requested changes

2022-02-24 17:20 UTC, santy289 commented on README.md
> -- [Santiago Valencia](profiles/santiago-valencia-profile.md)
Debes corregir los cambios en las lineas de codigo acá, ya que generaconflicto.

2022-02-24 17:36 UTC, AlexSuarezRodriguez commented on profiles/wendy-medina.md
> +> En una escala de 1 a 5 como te sientes tecnicamente en esto temas:  ⭐️⭐️⭐️⭐️⭐️
wendy ten presente tu conocimiento actualmente con los temas tecnicos de programacion,reviso los items siguientes y tienes un valor diferente corrigelo,de igual manera dentro de poco esos temas los vas a dominar al 100%.

2022-03-01 15:56 UTC, khriztianmoreno approved these changes

2022-03-01 15:57 UTC, merged